language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t jaeha23/docker-pumasi-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true jaeha23/docker-pumasi-app npm run test

after_success:
  - docker build -t jaeha23/docker-frontend ./frontend
  - docker build -t jaeha23/docker-backend ./backend
  - docker build -t jaeha23/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push jaeha23/docker-frontend
  - docker push jaeha23/docker-backend
  - docker push jaeha23/docker-nginx
deploy:
  provider: elasticbeanstalk
  region: ""
  app: "docker-pumasi-app"
  env: "DockerFullstackApp-env"
  bucket_name:
  bucket_path: "docker-pumasi-app"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
