version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"

  backend:
    links:
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - /app/node_modules
      - ./backend:/app

  mongo:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./mongo
    ports:
      - "27017:27017"
